# 端口
server:
  port: 8090

# 配置数据库
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.117.77.53:3310/fanyinjie?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver


# 配置mybatis
mybatis:
  type-aliases-package: com.fyj.demo.dto
  mapper-locations: classpath:mybatis_mapper/*.xml


# showSql
logging:
  level:
    com:
      fyj:
        demo:
          mapper: debug

sqlMapperPackage: mybatis_mapper
